
title: Algorea DevDoc
url: "//france-ioi.github.io"
baseurl: "/algorea-devdoc"

remote_theme: just-the-docs/just-the-docs@v0.10.0
# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/France-ioi/algorea-devdoc" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately

search_enabled: true
permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
